/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rubinics.sampleproj;

public class Application {
   public static void main(String[] args) {
	   System.out.println("Application");
   }
}
